"use client";
import Link from "next/link";
import {useLocale,useTranslations} from "next-intl";
import {useRouter} from "next/navigation";
import {useState} from "react";
import {toast} from "sonner";
import {demoMode} from "./api-client";
import {ValidationFeedback} from "./validation-feedback";
import {Button} from "./ui/button";
import {Input} from "./ui/input";
import {Label} from "./ui/label";

type Mode="login"|"signup"|"forgot"|"reset";
export function AuthForm({mode}:{mode:Mode}){const t=useTranslations("Auth"),v=useTranslations("Validation"),locale=useLocale(),router=useRouter();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [fieldErrors,setFieldErrors]=useState<Record<string,string>>({});
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget),email=String(data.get("email")||""),password=String(data.get("password")||"");const next:Record<string,string>={};if(mode!=="reset"&&!/^\S+@\S+\.\S+$/.test(email))next.email=v("email");if(mode!=="forgot"&&password.length<8)next.password=v("password");setFieldErrors(next);setError("");if(Object.keys(next).length)return;setBusy(true);
  try{if(demoMode){toast.success(t("demoSuccess"));router.push(`/${locale}/${mode==="signup"?"onboarding":"calendar"}`);return}const {createClient}=await import("@/lib/supabase/client");const supabase=createClient();let result;
   if(mode==="login")result=await supabase.auth.signInWithPassword({email,password});else if(mode==="signup")result=await supabase.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/${locale}/auth/callback`}});else if(mode==="forgot")result=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/${locale}/auth/callback?next=${encodeURIComponent(`/${locale}/reset-password`)}`});else result=await supabase.auth.updateUser({password});
   if(result.error)throw result.error;if(mode==="login"||mode==="reset")router.push(`/${locale}/calendar`);else router.push(`/${locale}/auth/result?kind=${mode}`);
   }catch(caught){const code=typeof caught==="object"&&caught&&"code" in caught?String(caught.code):"";if(code==="invalid_credentials")setFieldErrors({password:t("invalidCredentials")});else if(code==="email_not_confirmed")setFieldErrors({email:t("emailNotConfirmed")});else if(code==="weak_password")setFieldErrors({password:v("password")});else if(code==="same_password")setFieldErrors({password:t("samePassword")});else if(code==="session_not_found")setError(t("sessionExpired"));else if(code==="over_request_rate_limit")setError(t("rateLimited"));else setError(t("unknownError"))}finally{setBusy(false)}}
 const title=t(`${mode}.title`),description=t(`${mode}.description`);
 return <form noValidate onSubmit={submit} className="space-y-4"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{description}</p></div>{mode!=="reset"&&<div className="space-y-2"><Label htmlFor="email">{t("email")}</Label><Input id="email" name="email" type="email" autoComplete="email" required placeholder="name@example.com" aria-invalid={!!fieldErrors.email} aria-describedby={fieldErrors.email?"email-error":undefined}/><ValidationFeedback id="email-error" message={fieldErrors.email}/></div>}{mode!=="forgot"&&<div className="space-y-2"><Label htmlFor="password">{t("password")}</Label><Input id="password" name="password" type="password" minLength={8} required autoComplete={mode==="login"?"current-password":"new-password"} aria-invalid={!!fieldErrors.password} aria-describedby={fieldErrors.password?"password-error":undefined}/><ValidationFeedback id="password-error" message={fieldErrors.password}/></div>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button disabled={busy} className="w-full">{busy?t("working"):t(`${mode}.submit`)}</Button><AuthLinks mode={mode} locale={locale} t={t}/></form>}
function AuthLinks({mode,locale,t}:{mode:Mode;locale:string;t:(key:string)=>string}){return <div className="space-y-2 text-center text-sm">{mode==="login"&&<><Link className="text-muted-foreground underline-offset-4 hover:underline" href={`/${locale}/forgot-password`}>{t("forgotLink")}</Link><p>{t("newHere")} <Link className="font-medium underline-offset-4 hover:underline" href={`/${locale}/signup`}>{t("signupLink")}</Link></p></>}{mode!=="login"&&<Link className="text-muted-foreground underline-offset-4 hover:underline" href={`/${locale}/login`}>{t("backLogin")}</Link>}</div>}
