"use client";
import {useEffect,useMemo,useState} from "react";import {addDays,addMonths,endOfMonth,endOfWeek,format,startOfMonth,startOfWeek} from "date-fns";import {arSA,enUS} from "date-fns/locale";import {ChevronLeft,ChevronRight,CalendarRange,Rows3,LoaderCircle,X} from "lucide-react";import {useLocale,useTranslations} from "next-intl";import {getCalendar} from "./api-client";import type {CalendarDay,CalendarItem} from "./demo-data";import {TaskCard} from "./task-card";import {Alert} from "./ui/alert";import {Button} from "./ui/button";

type View="month"|"week";
export function CalendarDashboard(){const t=useTranslations("Calendar"),locale=useLocale(),dfLocale=locale==="ar"?arSA:enUS,[view,setView]=useState<View>("month"),[anchor,setAnchor]=useState(new Date()),[days,setDays]=useState<CalendarDay[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<string|null>(null),[requestKey,setRequestKey]=useState(0);const weekStartsOn=6 as const;
 const range=useMemo(()=>view==="month"?{start:startOfWeek(startOfMonth(anchor),{weekStartsOn}),end:endOfWeek(endOfMonth(anchor),{weekStartsOn})}:{start:startOfWeek(anchor,{weekStartsOn}),end:endOfWeek(anchor,{weekStartsOn})},[anchor,view]);
 const startIso=format(range.start,"yyyy-MM-dd"),endIso=format(range.end,"yyyy-MM-dd");
 useEffect(()=>{let active=true;getCalendar(startIso,endIso).then(raw=>{if(!active)return;const body=raw as {days?:CalendarDay[]};setDays(body.days||[]);setError("")}).catch(e=>active&&setError(e instanceof Error?e.message:t("error"))).finally(()=>active&&setLoading(false));return()=>{active=false}},[startIso,endIso,requestKey,t]);
 function move(delta:number){setLoading(true);setAnchor(view==="month"?addMonths(anchor,delta):addDays(anchor,delta*7))}function update(date:string,next:CalendarItem){setDays(ds=>ds.map(d=>d.date===date?{...d,items:d.items.map(i=>i.id===next.id?next:i)}:d))}
 const byDate=new Map(days.map(d=>[d.date,d]));const gridDates=eachDay(range.start,range.end);const selectedDay=selected?byDate.get(selected):undefined;
 return <div className="mx-auto max-w-[1500px] p-4 sm:p-6"><header className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-muted-foreground">{t("eyebrow")}</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">{view==="month"?format(anchor,"LLLL yyyy",{locale:dfLocale}):t("weekOf",{date:format(range.start,"PP",{locale:dfLocale})})}</h1></div><div className="flex items-center gap-2"><div className="flex rounded-lg border bg-background p-1"><Button aria-label={t("month")} size="sm" variant={view==="month"?"secondary":"ghost"} onClick={()=>setView("month")}><CalendarRange className="size-4"/><span className="hidden sm:inline">{t("month")}</span></Button><Button aria-label={t("week")} size="sm" variant={view==="week"?"secondary":"ghost"} onClick={()=>setView("week")}><Rows3 className="size-4"/><span className="hidden sm:inline">{t("week")}</span></Button></div><Button size="icon" variant="outline" aria-label={t("previous")} onClick={()=>move(-1)}><ChevronLeft className="size-4 rtl:rotate-180"/></Button><Button size="icon" variant="outline" aria-label={t("next")} onClick={()=>move(1)}><ChevronRight className="size-4 rtl:rotate-180"/></Button></div></header>
 {loading?<div className="grid min-h-64 place-items-center"><LoaderCircle className="size-7 animate-spin text-muted-foreground"/></div>:error?<Alert className="border-destructive/40 text-destructive">{error}<Button className="mt-3" size="sm" variant="outline" onClick={()=>{setLoading(true);setRequestKey(k=>k+1)}}>{t("retry")}</Button></Alert>:view==="month"?<MonthView dates={gridDates} byDate={byDate} locale={dfLocale} selected={selected} onSelect={setSelected} update={update} t={t}/>:<WeekView dates={gridDates} byDate={byDate} locale={dfLocale} update={update} t={t}/>} 
 {selected&&<div className="fixed inset-0 z-50 bg-foreground/20 md:hidden" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-label={t("dayDetails")} className="absolute inset-x-0 bottom-0 max-h-[82vh] overflow-auto rounded-t-2xl bg-background p-4 shadow-xl" onClick={e=>e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><div><p className="text-xs text-muted-foreground">{t("selectedDay")}</p><h2 className="text-lg font-semibold">{format(new Date(`${selected}T12:00:00`),"PPPP",{locale:dfLocale})}</h2></div><Button size="icon" variant="ghost" onClick={()=>setSelected(null)} aria-label={t("close")}><X className="size-5"/></Button></div><div className="space-y-3">{selectedDay?.items.length?selectedDay.items.map(i=><TaskCard key={i.id} item={i} date={selected} onChange={n=>update(selected,n)}/>):<Empty t={t("nothingScheduled")}/>}</div></section></div>}
 </div>}
// The translator remains in the month-view contract for localized empty states.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function MonthView({dates,byDate,locale,onSelect,update,t}:{dates:Date[];byDate:Map<string,CalendarDay>;locale:typeof enUS;selected:string|null;onSelect:(d:string)=>void;update:(d:string,i:CalendarItem)=>void;t:(k:string)=>string}){const weekdays=dates.slice(0,7);return <><div className="grid grid-cols-7 border-e border-b bg-muted/50">{weekdays.map(d=><div key={d.toISOString()} className="border-s border-t p-2 text-center text-xs font-medium text-muted-foreground">{format(d,"EEE",{locale})}</div>)}</div><div className="grid grid-cols-7 border-e border-b bg-background">{dates.map(d=>{const iso=format(d,"yyyy-MM-dd"),day=byDate.get(iso),outside=d.getMonth()!==dates[Math.floor(dates.length/2)].getMonth();return <button key={iso} onClick={()=>onSelect(iso)} className={`min-h-20 border-s border-t p-1.5 text-start md:min-h-40 md:p-2 ${outside?"bg-muted/30 text-muted-foreground":""}`}><span className={`inline-grid size-6 place-items-center rounded-full text-xs ${iso===format(new Date(),"yyyy-MM-dd")?"bg-primary text-primary-foreground":""}`}>{format(d,"d",{locale})}</span><div className="mt-1 flex gap-1 md:hidden">{day?.items.slice(0,3).map(i=><span key={i.id} className={`size-2 rounded-full bg-chart-${i.color}`}/>)}</div><div className="mt-1 hidden space-y-1.5 md:block">{day?.items.slice(0,2).map(i=><TaskCard key={i.id} item={i} date={iso} compact onChange={n=>update(iso,n)}/>)}</div></button>})}</div></>}
function WeekView({dates,byDate,locale,update,t}:{dates:Date[];byDate:Map<string,CalendarDay>;locale:typeof enUS;update:(d:string,i:CalendarItem)=>void;t:(k:string)=>string}){const [active,setActive]=useState(format(new Date(),"yyyy-MM-dd"));const effective=dates.some(d=>format(d,"yyyy-MM-dd")===active)?active:format(dates[0],"yyyy-MM-dd");return <><div className="mb-4 grid grid-cols-7 gap-1 md:hidden">{dates.map(d=>{const iso=format(d,"yyyy-MM-dd");return <button key={iso} onClick={()=>setActive(iso)} className={`rounded-lg p-2 text-center ${effective===iso?"bg-primary text-primary-foreground":"bg-secondary"}`}><span className="block text-[10px]">{format(d,"EEE",{locale})}</span><span className="text-sm font-semibold">{format(d,"d",{locale})}</span></button>})}</div><div className="space-y-4 md:hidden"><DayStack date={effective} day={byDate.get(effective)} locale={locale} update={update} t={t}/></div><div className="hidden grid-cols-7 gap-3 md:grid">{dates.map(d=>{const iso=format(d,"yyyy-MM-dd");return <DayStack key={iso} date={iso} day={byDate.get(iso)} locale={locale} update={update} t={t}/>})}</div></>}
function DayStack({date,day,locale,update,t}:{date:string;day?:CalendarDay;locale:typeof enUS;update:(d:string,i:CalendarItem)=>void;t:(k:string)=>string}){const d=new Date(`${date}T12:00:00`);return <section className="min-w-0"><div className="mb-2"><p className="text-xs uppercase tracking-wide text-muted-foreground">{format(d,"EEEE",{locale})}</p><h2 className="font-semibold">{format(d,"MMM d",{locale})}</h2></div><div className="space-y-3">{day?.items.length?day.items.map(i=><TaskCard key={i.id} item={i} date={date} onChange={n=>update(date,n)}/>):<Empty t={t("nothingScheduled")}/>}</div></section>}
function Empty({t}:{t:string}){return <div className="rounded-lg border border-dashed p-4 text-center text-xs text-muted-foreground">{t}</div>}
function eachDay(start:Date,end:Date){const result:Date[]=[];let d=start;while(d<=end){result.push(d);d=addDays(d,1)}return result}
