"use client";
import {useEffect,useMemo,useState} from "react";
import {Archive,ArchiveRestore,LoaderCircle,Plus,Save,Trash2} from "lucide-react";
import {useTranslations} from "next-intl";
import {toast} from "sonner";
import type {ChecklistOperation,FocusItem,IsoDate} from "@/types/domain";
import {effectiveChecklist} from "@/lib/domain/progress";
import {todayInTimeZone} from "@/lib/domain/dates";
import {apiFetch,getAreaGoals,getAreas,getFocusItems} from "./api-client";
import {Badge} from "./ui/badge";import {Button} from "./ui/button";import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "./ui/card";import {Input} from "./ui/input";import {Label} from "./ui/label";import {Progress} from "./ui/progress";import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "./ui/select";
type Area={id:string;name:string;position:number;archivedAt?:string|null};type Period="day"|"week"|"month"|"year";type Goal={id:string;areaId:string;period:Period;targetMinutes:number;actualMinutes:number;percent:number;periodStart:string;periodEnd:string};
const NONE="unassigned",periods:Period[]=["day","week","month","year"];
// Checklist changes remain effective-dated so historical completions are untouched.
function ChecklistEditor({item,effectiveFrom,busy,onSave,t}:{item:FocusItem;effectiveFrom:IsoDate;busy:boolean;onSave:(item:FocusItem,ops:ChecklistOperation[])=>void;t:(key:string)=>string}){const [newStep,setNewStep]=useState("");const steps=effectiveChecklist(item.checklist,effectiveFrom);return <div className="space-y-2 sm:col-span-4"><Label>{t("checklist")}</Label>{steps.map(step=><div key={step.id} className="flex items-center gap-2"><span className="flex-1 text-sm">{step.label}</span><Button size="sm" variant="ghost" disabled={busy} onClick={()=>onSave(item,[{operation:"retire",id:step.id,effectiveFrom}])}>{t("retireStep")}</Button></div>)}<div className="flex gap-2"><Input aria-label={t("newStep")} value={newStep} onChange={e=>setNewStep(e.target.value)}/><Button size="sm" disabled={busy||!newStep.trim()} onClick={()=>{onSave(item,[{operation:"add",label:newStep,position:steps.length,effectiveFrom}]);setNewStep("")}}>{t("addStep")}</Button></div></div>}
export function FocusItemManager({timezone:_timezone}:{timezone:string}){const t=useTranslations("FocusManager");const [areas,setAreas]=useState<Area[]>([]),[items,setItems]=useState<FocusItem[]>([]),[goals,setGoals]=useState<Goal[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[areaName,setAreaName]=useState(""),[taskName,setTaskName]=useState(""),[taskArea,setTaskArea]=useState(NONE),[effectiveFrom,setEffectiveFrom]=useState<IsoDate>(()=>todayInTimeZone(_timezone));
useEffect(()=>{Promise.all([getAreas(true),getFocusItems(true),getAreaGoals()]).then(([a,i,g])=>{setAreas(a);setItems(i);setGoals(g)}).catch(()=>toast.error(t("error"))).finally(()=>setLoading(false))},[t]);
const activeAreas=useMemo(()=>areas.filter(a=>!a.archivedAt).sort(byPosition),[areas]),archivedAreas=areas.filter(a=>a.archivedAt).sort(byPosition),activeItems=items.filter(i=>!i.archivedAt).sort(byPosition),archivedItems=items.filter(i=>i.archivedAt).sort(byPosition);
async function createArea(){if(!areaName.trim())return;setBusy(true);try{const a=await apiFetch<Area>("/api/v1/areas",{method:"POST",body:JSON.stringify({name:areaName,position:activeAreas.length})});setAreas(v=>[...v,a]);setAreaName("");toast.success(t("createdArea"))}catch{toast.error(t("error"))}finally{setBusy(false)}}
async function createTask(){if(!taskName.trim())return;setBusy(true);try{const i=await apiFetch<FocusItem>("/api/v1/focus-items",{method:"POST",body:JSON.stringify({name:taskName,areaId:taskArea===NONE?null:taskArea,position:activeItems.length,checklist:[]})});setItems(v=>[...v,i]);setTaskName("");toast.success(t("createdTask"))}catch{toast.error(t("error"))}finally{setBusy(false)}}
async function patchArea(a:Area,changes:Record<string,unknown>){setBusy(true);try{const next=await apiFetch<Area>("/api/v1/areas",{method:"PATCH",body:JSON.stringify({id:a.id,...changes})});setAreas(v=>v.map(x=>x.id===a.id?next:x));toast.success(t("saved"))}catch{toast.error(t("error"))}finally{setBusy(false)}}
async function patchTask(i:FocusItem,changes:Record<string,unknown>){setBusy(true);try{const next=await apiFetch<FocusItem>("/api/v1/focus-items",{method:"PATCH",body:JSON.stringify({id:i.id,...changes})});setItems(v=>v.map(x=>x.id===i.id?next:x));if("areaId" in changes)setGoals(await getAreaGoals());toast.success(t("saved"))}catch{toast.error(t("error"))}finally{setBusy(false)}}
async function maintainChecklist(item:FocusItem,checklistOperations:ChecklistOperation[]){setBusy(true);try{const next=await apiFetch<FocusItem>("/api/v1/focus-items",{method:"PATCH",body:JSON.stringify({id:item.id,checklistOperations})});setItems(v=>v.map(x=>x.id===item.id?next:x));toast.success(t("saved"))}catch{toast.error(t("error"))}finally{setBusy(false)}}
async function saveGoal(areaId:string,period:Period,targetMinutes:number){if(!Number.isInteger(targetMinutes)||targetMinutes<1)return;setBusy(true);try{const g=await apiFetch<Goal>("/api/v1/area-goals",{method:"PUT",body:JSON.stringify({areaId,period,targetMinutes})});setGoals(v=>[...v.filter(x=>!(x.areaId===areaId&&x.period===period)),g]);toast.success(t("goalSaved"))}catch{toast.error(t("goalError"))}finally{setBusy(false)}}
async function deleteGoal(g:Goal){setBusy(true);try{await apiFetch("/api/v1/area-goals",{method:"DELETE",body:JSON.stringify({id:g.id})});setGoals(v=>v.filter(x=>x.id!==g.id));toast.success(t("goalDeleted"))}catch{toast.error(t("goalError"))}finally{setBusy(false)}}
if(loading)return <Card><CardContent className="grid min-h-48 place-items-center"><LoaderCircle className="size-6 animate-spin"/></CardContent></Card>;
return <div className="space-y-5"><Card><CardHeader><CardTitle>{t("title")}</CardTitle><CardDescription>{t("description")}</CardDescription></CardHeader><CardContent className="grid gap-4 lg:grid-cols-2"><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><Input aria-label={t("areaName")} value={areaName} onChange={e=>setAreaName(e.target.value)} placeholder={t("areaPlaceholder")}/><Button disabled={busy||!areaName.trim()} onClick={createArea}><Plus className="size-4"/>{t("addArea")}</Button></div><div className="grid gap-2 sm:grid-cols-[1fr_10rem_auto]"><Input aria-label={t("taskName")} value={taskName} onChange={e=>setTaskName(e.target.value)} placeholder={t("taskPlaceholder")}/><AreaSelect value={taskArea} areas={activeAreas} label={t("areaAssignment")} unassigned={t("unassigned")} onChange={setTaskArea}/><Button disabled={busy||!taskName.trim()} onClick={createTask}><Plus className="size-4"/>{t("addTask")}</Button></div><div className="max-w-xs"><Label htmlFor="checklist-effective-from">{t("effectiveFrom")}</Label><Input id="checklist-effective-from" type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value as IsoDate)}/></div></CardContent></Card>
{[...activeAreas,...archivedAreas,{id:NONE,name:t("unassigned"),position:999999}].map(a=>{const grouped=activeItems.filter(i=>(i.areaId??NONE)===a.id);return <Card key={a.id}><CardHeader><div className="flex items-center justify-between"><CardTitle>{a.name}</CardTitle>{a.id!==NONE&&!a.archivedAt&&<Button size="sm" variant="ghost" disabled={busy} onClick={()=>patchArea(a,{archived:true})}><Archive className="size-4"/>{t("archiveArea")}</Button>}</div></CardHeader><CardContent className="space-y-4">{a.id!==NONE&&<GoalEditor areaId={a.id} goals={goals.filter(g=>g.areaId===a.id)} busy={busy} t={t} save={saveGoal} remove={deleteGoal}/>} {grouped.length?grouped.map(i=><TaskEditor key={i.id} item={i} areas={areas} busy={busy} t={t} patch={patchTask} effectiveFrom={effectiveFrom} maintain={maintainChecklist}/>):<p className="text-sm text-muted-foreground">{t("noTasks")}</p>}</CardContent></Card>})}
<Card><CardHeader><CardTitle>{t("archived")}</CardTitle><CardDescription>{t("archivedDescription")}</CardDescription></CardHeader><CardContent>{[...archivedAreas.map(value=>({type:"area" as const,value})),...archivedItems.map(value=>({type:"task" as const,value}))].map(e=><div key={`${e.type}-${e.value.id}`} className="flex items-center justify-between border-b py-2"><span><Badge className="me-2">{t(e.type)}</Badge>{e.value.name}</span><Button size="sm" variant="outline" disabled={busy} onClick={()=>e.type==="area"?patchArea(e.value,{archived:false}):patchTask(e.value,{archived:false})}><ArchiveRestore className="size-4"/>{t("restore")}</Button></div>)}</CardContent></Card></div>}
function AreaSelect({value,areas,label,unassigned,onChange}:{value:string;areas:Area[];label:string;unassigned:string;onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent><SelectItem value={NONE}>{unassigned}</SelectItem>{areas.map(a=><SelectItem key={a.id} value={a.id}>{a.name}</SelectItem>)}</SelectContent></Select>}
function TaskEditor({item,areas,busy,t,patch,effectiveFrom,maintain}:{item:FocusItem;areas:Area[];busy:boolean;effectiveFrom:IsoDate;maintain:(item:FocusItem,ops:ChecklistOperation[])=>void;t:(k:string,v?:Record<string,string|number|Date>)=>string;patch:(i:FocusItem,c:Record<string,unknown>)=>void}){const [name,setName]=useState(item.name);return <div className="grid gap-2 rounded-lg border p-3 sm:grid-cols-[1fr_12rem_auto_auto]"><Input aria-label={t("renameTask")} value={name} onChange={e=>setName(e.target.value)}/><AreaSelect value={item.areaId??NONE} areas={areas} label={t("areaAssignment")} unassigned={t("unassigned")} onChange={v=>patch(item,{areaId:v===NONE?null:v})}/><Button size="icon" variant="outline" aria-label={t("saveName")} disabled={busy||!name.trim()||name===item.name} onClick={()=>patch(item,{name})}><Save className="size-4"/></Button><Button size="icon" variant="ghost" aria-label={t("archiveTask")} disabled={busy} onClick={()=>patch(item,{archived:true})}><Archive className="size-4"/></Button><ChecklistEditor item={item} effectiveFrom={effectiveFrom} busy={busy} onSave={maintain} t={t}/></div>}
function GoalEditor({areaId,goals,busy,t,save,remove}:{areaId:string;goals:Goal[];busy:boolean;t:(k:string,v?:Record<string,string|number|Date>)=>string;save:(a:string,p:Period,n:number)=>void;remove:(g:Goal)=>void}){return <section aria-label={t("goals")} className="grid gap-3 md:grid-cols-2">{periods.map(p=>{const goal=goals.find(g=>g.period===p);return <GoalRow key={`${p}-${goal?.targetMinutes??"new"}`} areaId={areaId} period={p} goal={goal} busy={busy} t={t} save={save} remove={remove}/>})}</section>}
function GoalRow({areaId,period,goal,busy,t,save,remove}:{areaId:string;period:Period;goal?:Goal;busy:boolean;t:(k:string,v?:Record<string,string|number|Date>)=>string;save:(a:string,p:Period,n:number)=>void;remove:(g:Goal)=>void}){const [target,setTarget]=useState(goal?.targetMinutes??60);return <div className="rounded-lg bg-muted/40 p-3"><div className="mb-2 flex items-center justify-between"><Label>{t(period)}</Label>{goal&&<Button size="icon" variant="ghost" aria-label={t("deleteGoal")} onClick={()=>remove(goal)}><Trash2 className="size-4"/></Button>}</div><div className="flex gap-2"><Input aria-label={t("goalTarget",{period:t(period)})} type="number" min="1" value={target} onChange={e=>setTarget(Number(e.target.value))}/><Button size="sm" disabled={busy||target<1} onClick={()=>save(areaId,period,target)}>{t("saveGoal")}</Button></div>{goal&&<><div className="mt-3 flex justify-between text-xs"><span>{t("goalProgress",{actual:goal.actualMinutes,target:goal.targetMinutes})}</span><span>{Math.min(100,goal.percent)}%</span></div><Progress className="mt-1" value={Math.min(100,goal.percent)}/></>}</div>}
function byPosition(a:{position:number;name:string},b:{position:number;name:string}){return a.position-b.position||a.name.localeCompare(b.name)}
